GitHub WorkFlow Triggers

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -6,12 +6,12 @@ jobs:
         steps:
             - name: Say Hello
               run: echo "Hellow, World!"
-    echo-goodbye:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Failed Step
-              run: | # "|" -> This vertical line Symbol is mandatory when we are defining multiline script
-                echo "I Will Fail"
-                exit 1
-            - name: Say goodbye
-              run: echo "Goodbye!"
+    # echo-goodbye:
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - name: Failed Step
+    #           run: | # "|" -> This vertical line Symbol is mandatory when we are defining multiline script
+    #             echo "I Will Fail"
+    #             exit 1
+    #         - name: Say goodbye
+    #           run: echo "Goodbye!"
